### ISSUE TITLE
Tạo placeholder khi kéo thả task

### ISSUE THREAD

**Issue by doankhanh122** [doankhanh122/NewZWeb-Demo#3]
- Khi kéo thả task cần hiện placeholder của task để biết task định thả ở đâu

**Comment by doankhanh122** [comment]
Chị @hangbk84 làm nhé
<img width="341" alt="image" src="https://github.com/user-attachments/assets/a62858c7-9138-4713-8fdf-d1720f8a1e42">

**Comment by hangbk84** [comment]
Fix this issue

**Comment by hangbk84** [comment]
Please review this issue
