### ISSUE TITLE
fix bug place holder

### ISSUE THREAD

**Issue by doankhanh122** [doankhanh122/NewZWeb-Demo#4]
<img width="261" alt="image" src="https://github.com/user-attachments/assets/427e2dc1-e645-43b3-999d-9df0c9119d06">

Nếu kéo thả task qua các cột thì placeholder hoạt động ok
Nhưng nếu kéo thả task trong cùng 1 cột (như ảnh) thì placeholder ko hoạt động đúng, như ảnh thì placeholder item23 phải hiện ở card trên cùng nhưng lại vẫn ở card dưới cùng

**Comment by hangbk84** [comment]
Fix this usse. Please review
